### ISSUE TITLE
Consider switching to gopacket/gopacket

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/pcap-release#11]
google/gopacket has become unmaintained as the original maintainer has left Google.

Consider making the switch to gopacket/gopacket, for details see https://github.com/google/gopacket/issues/1016

**Comment by maxmoehl** [comment]
Sounds good, however, I'd like to wait until v1 is released. Just to be safe.

PS: you probably meant to say "switch to [gopacket/gopacket](https://github.com/gopacket/gopacket)"
