### ISSUE TITLE
Auto-bump and document go versions

### ISSUE THREAD

**Issue by ameowlia** [cloudfoundry/pcap-release#16]
### Context
Most of the bosh releases in the ARP working group follow the same pattern for bumping go versions. They (1) have a pipeline that autobumps the go versions when it is released (2) they document the version number in a file called docs/go.version and (3) the version is printed in github release notes.

**Example**
* [Example autobump pipeline + task](https://gist.github.com/ameowlia/3378873307e7dd04c7dae87bdba3edb1) (This pipeline is just for reference, it will not run.)
* [Example autobump commit](https://github.com/cloudfoundry/routing-release/commit/1805b7bb441d3d2fd20365be85b48ce1f91e6554)
* [Example docs file](https://github.com/cloudfoundry/routing-release/blob/develop/docs/go.version)
* [Example release note](https://github.com/cloudfoundry/routing-release/releases/tag/v0.259.0)

I was chatting with the @cloudfoundry/toc about this practice at the weekly meeting yesterday and they thought (and I agree) that it would be great to standardize this across CF. This issue is a first step towards that point.

### Current State
Currently this release hardcodes go 1.18.5 ([1](https://github.com/cloudfoundry/pcap-release/blob/1930a51f4b21caac361c49a75205f4d8c9b23de5/packages/pcap-agent/packaging#L11), [2](https://github.com/cloudfoundry/pcap-release/blob/1930a51f4b21caac361c49a75205f4d8c9b23de5/packages/pcap-api/spec#L7)).

### Desired State
[ ] go is autobumped in CI
[ ] the go version is documented in docs/go.version
[ ] the go version is included in release notes (when a release happens) (emojis optional ✨ )

**Comment by plowin** [comment]
Thanks for raising this.
We will enhance this before/shortly after creating the first release!

**Comment by peanball** [comment]
Autobumps:
* Golang as golang-release vendored-package: #52 
  * includes writing `docs/go.version`
  * Release note mention of used golang version in: #69 
    
    ✨ Optional emoji used ;-)
* libpcap tarball blob bumping in: #38
* Dependabot for used golang libraries in: #32
